### ISSUE TITLE
VxScan not scanning when powered on in wrong order

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1476] opened 2022-03-04 16:59 UTC
VxScan not scanning when powered on in wrong order - ballots were not being scanned when the power cord is plugged in after the tablet is turned on where VxScan just doesn't suck them in at all. I was able to reproduce this on the scanner I was using when this came up, but we should investigate it further. If this is something out of our control to fix (I vaguely remember us discussing this before), we need to at least document the procedure for poll workers to make sure they can correct this (which is solved by just restarting the tablet).

Perhaps consider onscreen instruction?

**Comment by mattroe** [comment] 2022-03-04 23:22
I couldn't reproduce this on the precinct scanner I have at home.

**Comment by benadida** [comment] 2022-03-11 15:09
also cannot repro, blaming this on some bad scanners we had, and closing.

**Closed by benadida** 2022-03-11 15:09 UTC
Labels: bug
