### ISSUE TITLE
BMD: Close polls when switching precincts as an admin

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#419] opened 2021-04-01 19:45 UTC
When you switch precincts as an admin on BMD the tallies are cleared in memory but the polls remain "open" and no polls closed report is printed. 

We might want to couple changing this with making polls closed irreversible and adding a "end voting for the day" feature.

**Comment by eventualbuddha** [comment] 2021-04-01 19:58
Duplicate of #368

**Closed** 2021-04-01 19:58 UTC
Labels: [zube]: Inbox
