### ISSUE TITLE
"Manually Entered Results" is a little long and confusing for a title - could "Manual Tallies" be better? Then the action is "Add Manual Tallies" versus add manually entered results (this reads to me as add something that has already been entered

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#3759] opened 2023-07-26 03:53 UTC
"Manually Entered Results" is a little long and confusing for a title - could "Manual Tallies" be better? Then the action is "Add Manual Tallies" versus add manually entered results (this reads to me as add something that has already been entered...)

Issue automatically created from slack feedback reported by ginny 
https://votingworks.slack.com/archives/CJU9MSC6S/p1690299789210749?thread_ts=1690299789.210749&cid=CJU9MSC6S

**Comment by adghayes** [comment] 2023-11-22 17:18
Duplicate of #4255

**Closed by adghayes** 2023-11-22 17:18 UTC
Labels: triage
