### ISSUE TITLE
VxScan: BMD ballots take a long time (~20s) to interpret

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2296] opened 2022-08-08 22:38 UTC
On @mattroe's VxScan, BMD ballots are taking a very long time (~20) to interpret before being accepted. The end user experience is just a long Please Wait screen as shown here: https://votingworks.slack.com/archives/CEL6D3GAD/p1659992191056029?thread_ts=1659466716.613019&cid=CEL6D3GAD

A backup of scanned BMD images is available here: https://votingworks.slack.com/archives/CEL6D3GAD/p1659996283569829?thread_ts=1659663574.164549&cid=CEL6D3GAD

**Comment by carolinemodic** [comment] 2022-08-08 22:40
When I tested this it took a couple seconds, about the same time length as the hmpb, which is maybe a bit slower then I would expect but I forget what the baseline is.

**Comment by jonahkagan** [comment] 2022-08-08 22:42
Confirmed in the logs that the `interpretSheet` function invoked by the state machine took 20s to return.

**Comment by benadida** [comment] 2022-08-10 15:43
Should be partially addressed by #2307, otherwise we have to clean and calibrate the scanners.

**Comment by benadida** [comment] 2022-08-10 21:43
The central issue here is that, when the back of a BMD ballot, which is blank, has a lot of noise, then the QR code detectors take forever to find the absence of a QR code.

I think this is sufficiently resolved for m14. For future fixes, we should consider:
- parallelizing front & back QR code
- or, since of our 3 QR code detectors, the last one if particularly slow, we could try the first 2 on front and back, and if we get one side with a BMD ballot and the other one blank, then we can stop there. We would use the 3rd detector only if we can't see any QR code at all on either side with the faster QR code readers. This is a medium-sized change.
- find a better way to reduce noise?

**Comment by benadida** [comment] 2022-08-10 23:34
fixed in #2315.

**Closed by benadida** 2022-08-10 23:34 UTC
Labels: bug
