### ISSUE TITLE
Precinct scanner adjudication not rejecting properly?

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1099] opened 2021-10-21 16:10 UTC
@ginvdr said:

> I was able to scan a blank and overvoted ballot with no prompt of an error.

- [Slack thread](https://votingworks.slack.com/archives/CJU9MSC6S/p1634761435082000)
- [election definition](https://github.com/votingworks/election-definitions/blob/07118d0d93dfadecde26a50347c9ff337bd42f29/2021-municipal-general-elections/sample-election/test-municipal-election.json)

**Comment by carolinemodic** [comment] 2022-02-13 18:47
Closing this as a duplicate of https://github.com/votingworks/vxsuite/issues/1421

**Closed as completed by carolinemodic** 2022-02-13 18:47 UTC
Labels: bug
