### ISSUE TITLE
Reconsider polls closing after restart

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1968] opened 2022-06-16 14:55 UTC
• If you open the polls but later need to restart VxScan, why does it ask you to open the polls again? Does VxScan know about the polls open/closed state? Should this persist across restarts?

Issue automatically created from slack feedback reported by jonah 
https://votingworks.slack.com/archives/CJU9MSC6S/p1654113282618489?thread_ts=1654113282.618489&cid=CJU9MSC6S

**Comment by benadida** [comment] 2022-06-16 14:57
dupe of #1948 :)

**Closed by benadida** 2022-06-16 14:57 UTC
Labels: triage
