### ISSUE TITLE
Investigate test failure in libs/ui/set_clock

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2843] opened 2022-12-02 16:35 UTC
Noticed a fast-check failure in this test that could potentially be a bug - https://app.circleci.com/pipelines/github/votingworks/vxsuite/6690/workflows/7f66e9d1-5090-455c-9679-61aa58c3c87b/jobs/163905/tests

Needs investigation/fix

**Comment by adghayes** [comment] 2022-12-12 17:17
Duplicate of #2825

**Closed by adghayes** 2022-12-12 17:17 UTC
Labels: tech-improvement
