### ISSUE TITLE
upgrade `react` & related packages

### ISSUE THREAD

**Issue by eventualbuddha** [votingworks/vxsuite#1805] opened 2022-05-09 18:38 UTC
We're on React v17 and should upgrade to v18. This also includes any surrounding packages for routing, testing, components, etc.

**Comment by adghayes** [comment] 2022-11-30 18:40
Duplicate of #1660

**Comment by adghayes** [comment] 2023-07-20 23:18
Closing in favor of #1660.

**Closed by adghayes** 2023-07-20 23:18 UTC
Labels: tech-improvement
