### ISSUE TITLE
VxMark: If you insert a blank sheet of paper in the "insert printed ballot" flow you are just returned to the pollworker screen with no message

### ISSUE THREAD

**Issue by arsalansufi** [votingworks/vxsuite#5212] opened 2024-08-05 17:43 UTC
VxMark: If you insert a blank sheet of paper in the "insert printed ballot" flow you are just returned to the pollworker screen with no message. Then if you start a voting session it just skips the loading paper flow as it can tell it already has paper ready to go

Issue automatically created from Slack feedback reported by caroline: 
https://votingworks.slack.com/archives/CJU9MSC6S/p1722455020334169?thread_ts=1722455020.334169&cid=CJU9MSC6S

**Comment by adghayes** [comment] 2024-08-05 18:02
oops - duplicate of #5148

**Closed** 2024-08-05 18:02 UTC
Labels: triage
