### ISSUE TITLE
nh-accuvote converter: cannot load NH demo files into VxAdmin

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2044] opened 2022-06-30 21:44 UTC
## Description
When you load VxAdmin with the [NH demo source XML & PDF files](https://github.com/votingworks/election-definitions/tree/main/2022-07-12-nh-demo), one file will load but the second file will not be accepted. A user cannot program VxAdmin through the conversion flow.

A video of this behavior is here: https://votingworks.slack.com/archives/C02Q3M874SV/p1655490232718929?thread_ts=1655478253.188959&cid=C02Q3M874SV

## Repro
1. Select convert from NH on VxAdmin election definition loading screen
2. [Load the XML & PDF files](https://github.com/votingworks/election-definitions/tree/main/2022-07-12-nh-demo)

## Expected behavior
VxAdmin programs to election definition f0b66d8a41

## Screenshots
Video of bug: https://votingworks.slack.com/archives/C02Q3M874SV/p1655490232718929?thread_ts=1655478253.188959&cid=C02Q3M874SV

**Comment by benadida** [comment] 2022-07-03 17:10
confirmed that this is because of the template size not having a 0.5" margin. Going to try to update the PDF template file we have.

**Comment by benadida** [comment] 2022-07-03 17:40
fixed by:
https://github.com/votingworks/election-definitions/pull/109

**Closed** 2022-07-05 19:01 UTC
Labels: bug
