### ISSUE TITLE
"Card reader not detected" error

### ISSUE THREAD

**Issue by mcchilders** [votingworks/vxsuite#1473] opened 2022-03-04 16:40 UTC
We're still having problems with the card reader not being detected even when it is plugged in: see this thread for videos/details: https://votingworks.slack.com/archives/CJU9MSC6S/p1645220156029639

From Drew:
"Today was the third time I’ve seen this “Card Reader Not Detected” issue for m13a. VxScan will not be able to detect the card reader and needs to be rebooted or the card reader USB cord needs to be unplugged and re-plugged into the hub. I’ve seen this happen while the blue light on the card reader was lit up too.

Originally I thought it was due to the re-orientation of the hub, but I changed the orientation again and that seems unlikely. It seems to me it either has to do with the different USB-C extension cable I’m using or it’s a software issue."

**Comment by benadida** [comment] 2022-03-09 13:39
@adghayes I have seen no evidence that this is a hardware issue, assigning this to you to provide any insight on cabling to see if you can repro in any way.

**Comment by adghayes** [comment] 2022-03-10 21:13
I believe it is a hardware issue. Unable to reproduce after comparing precinct scanners with the different cabling. We are going with the cables that we've had more success with for m13b. We will see the frequency of the issue once we get to production QA.

**Comment by benadida** [comment] 2022-04-28 13:03
closing as this is not a significant issue anymore.

**Closed by benadida** 2022-04-28 13:03 UTC
Labels: bug
