### ISSUE TITLE
nh-accuvote VxScan: cannot unconfigure

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxsuite#2051] opened 2022-07-01 00:45 UTC
## Description
Unconfiguring never completes and continually presents a Loading... screen when unconfiguring VxScan loaded with the NH ballot package (f0b66d8a41). I cannot reproduce this issue with other ballot packages.

## Repro
1. Tested on main on 6/30
2. Configure VxScan with NH ballot package (f0b66d8a41)
3. Insert admin card, click unconfigure, and confirm
4. See loading screen

**Comment by mattroe** [comment] 2022-07-02 20:32
Marking as medium priority as we likely won't be configuring/unconfiguring during BLC demo.

**Comment by benadida** [comment] 2022-07-05 15:27
This is due to the blocker we put in to prevent export when backups and CVRs hasn't been taken. Of course this should present an error message, not just silently fail, but that's the cause.

This can be addressed in the following way:
- switch to test mode, then unconfiguring is not gated.
- export results *and* export backups, then unconfiguring should work.

**Closed** 2022-07-06 18:32 UTC
Labels: bug
