### ISSUE TITLE
Central System: USB hubs that work consistently across many USB sticks

### ISSUE THREAD

**Issue by carolinemodic** [votingworks/vxsuite#1938] opened 2022-06-08 01:06 UTC
Drew reports that our USB hubs aren't breaking but there is some incompatibility between our hubs and our USB drives.

We have our hub working fine for our peripherals, but the drive wasn't detected through it. Switched to the port on the computer, and it worked fine.

Issue automatically created from slack feedback reported by ben 
https://votingworks.slack.com/archives/CJU9MSC6S/p1654650399748139

**Comment by adghayes** [comment] 2022-08-09 19:30
Not able to reproduce this today on VxDev, I think I will have to try on a locked down version. This is not actually tied to the code freeze, just needs to get done before field updates.

**Comment by mattroe** [comment] 2022-09-03 17:35
@adghayes did we determine this wasn't actually a problem? if so, close and feel free to also complete the roadmap issue: https://github.com/votingworks/vxsuite-roadmap/issues/56

**Comment by adghayes** [comment] 2022-09-07 00:11
I am unable to reproduce the issue on locked down VxAdmin in the Bakery, with the same USB drives and hub. I am closing this issue. We can re-open if we see more issues or are able to reproduce.

**Closed by adghayes** 2022-09-07 00:11 UTC
Labels: hardware
